// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/fruits/good-building-system/:id": {
    params: {
      "id": string;
    };
  };
  "/fruits/good-building-system/new": {
    params: {};
  };
  "/fruits/good-building-system": {
    params: {};
  };
  "/tools/frames-volume-calc": {
    params: {};
  };
  "/tools/grade-differential": {
    params: {};
  };
  "/tools/building-envelope": {
    params: {};
  };
  "/grandpas-cabin-recipe": {
    params: {};
  };
  "/tools/thermal-inertia": {
    params: {};
  };
  "/fruits/all-projects": {
    params: {};
  };
  "/fruits/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/tools/erv-calculator": {
    params: {};
  };
  "/tools/space-layout": {
    params: {};
  };
  "/fruits/daily-log": {
    params: {};
  };
  "/good/architecture": {
    params: {};
  };
  "/tools/do-not-use": {
    params: {};
  };
  "/good/consulting": {
    params: {};
  };
  "/assemblies/:id": {
    params: {
      "id": string;
    };
  };
  "/docs/wc-waiver": {
    params: {};
  };
  "/fruits/styles": {
    params: {};
  };
  "/good/sunny-no1": {
    params: {};
  };
  "/sunny-home-no1": {
    params: {};
  };
  "/fruits/vault": {
    params: {};
  };
  "/good/building": {
    params: {};
  };
  "/materials/:id": {
    params: {
      "id": string;
    };
  };
  "/card/:fileId": {
    params: {
      "fileId": string;
    };
  };
  "/roots": {
    params: {};
  };
  "/tools": {
    params: {};
  };
  "/good/guides": {
    params: {};
  };
  "/science/:id": {
    params: {
      "id": string;
    };
  };
  "/stories/:id": {
    params: {
      "id": string;
    };
  };
  "/tools/loads": {
    params: {};
  };
  "/api/upload": {
    params: {};
  };
  "/api/upload/presign": {
    params: {};
  };
  "/magic-link": {
    params: {};
  };
  "/api/vault": {
    params: {};
  };
  "/api/vault/multipart-complete": {
    params: {};
  };
  "/api/vault/download/:fileId": {
    params: {
      "fileId": string;
    };
  };
  "/api/vault/archive-cleanup": {
    params: {};
  };
  "/api/vault/multipart-abort": {
    params: {};
  };
  "/api/vault/multipart-init": {
    params: {};
  };
  "/api/vault/multipart-part": {
    params: {};
  };
  "/api/vault/:fileId": {
    params: {
      "fileId": string;
    };
  };
  "/api/vault/folders": {
    params: {};
  };
  "/api/vault/folders/:folderId": {
    params: {
      "folderId": string;
    };
  };
  "/api/vault/presign": {
    params: {};
  };
  "/api/vault/upload": {
    params: {};
  };
  "/tools/mtf": {
    params: {};
  };
  "/scc-demo": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/explore": {
    params: {};
  };
  "/fruits": {
    params: {};
  };
  "/good/s": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/health/:key?": {
    params: {
      "key"?: string;
    };
  };
  "/logout": {
    params: {};
  };
  "/verify": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/mrgnt": {
    params: {};
  };
  "/mrgnt/projects": {
    params: {};
  };
  "/mrgnt/discord": {
    params: {};
  };
  "/mrgnt/humans": {
    params: {};
  };
  "/mrgnt/gbs": {
    params: {};
  };
  "/path": {
    params: {};
  };
  "/path/faq-1": {
    params: {};
  };
  "/path/faq-2": {
    params: {};
  };
  "/path/faq-3": {
    params: {};
  };
  "/path/faq-4": {
    params: {};
  };
  "/path/faq-5": {
    params: {};
  };
  "/path/faq-6": {
    params: {};
  };
  "/path/faq-7": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/fruits/good-building-system/:id" | "/fruits/good-building-system/new" | "/fruits/good-building-system" | "/tools/frames-volume-calc" | "/tools/grade-differential" | "/tools/building-envelope" | "/grandpas-cabin-recipe" | "/tools/thermal-inertia" | "/fruits/all-projects" | "/fruits/projects/:id" | "/tools/erv-calculator" | "/tools/space-layout" | "/fruits/daily-log" | "/good/architecture" | "/tools/do-not-use" | "/good/consulting" | "/assemblies/:id" | "/docs/wc-waiver" | "/fruits/styles" | "/good/sunny-no1" | "/sunny-home-no1" | "/fruits/vault" | "/good/building" | "/materials/:id" | "/card/:fileId" | "/roots" | "/tools" | "/good/guides" | "/science/:id" | "/stories/:id" | "/tools/loads" | "/api/upload" | "/api/upload/presign" | "/magic-link" | "/api/vault" | "/api/vault/multipart-complete" | "/api/vault/download/:fileId" | "/api/vault/archive-cleanup" | "/api/vault/multipart-abort" | "/api/vault/multipart-init" | "/api/vault/multipart-part" | "/api/vault/:fileId" | "/api/vault/folders" | "/api/vault/folders/:folderId" | "/api/vault/presign" | "/api/vault/upload" | "/tools/mtf" | "/scc-demo" | "/contact" | "/explore" | "/fruits" | "/good/s" | "/health" | "/health/:key?" | "/logout" | "/verify" | "/about" | "/login" | "/mrgnt" | "/mrgnt/projects" | "/mrgnt/discord" | "/mrgnt/humans" | "/mrgnt/gbs" | "/path" | "/path/faq-1" | "/path/faq-2" | "/path/faq-3" | "/path/faq-4" | "/path/faq-5" | "/path/faq-6" | "/path/faq-7";
  };
  "routes/fruits_.good-building-system_.$id.tsx": {
    id: "routes/fruits_.good-building-system_.$id";
    page: "/fruits/good-building-system/:id";
  };
  "routes/fruits_.good-building-system_.new.tsx": {
    id: "routes/fruits_.good-building-system_.new";
    page: "/fruits/good-building-system/new";
  };
  "routes/fruits_.good-building-system.tsx": {
    id: "routes/fruits_.good-building-system";
    page: "/fruits/good-building-system";
  };
  "routes/tools.frames-volume-calc.tsx": {
    id: "routes/tools.frames-volume-calc";
    page: "/tools/frames-volume-calc";
  };
  "routes/tools.grade-differential.tsx": {
    id: "routes/tools.grade-differential";
    page: "/tools/grade-differential";
  };
  "routes/tools.building-envelope.tsx": {
    id: "routes/tools.building-envelope";
    page: "/tools/building-envelope";
  };
  "routes/grandpas-cabin-recipe.tsx": {
    id: "routes/grandpas-cabin-recipe";
    page: "/grandpas-cabin-recipe";
  };
  "routes/tools.thermal-inertia.tsx": {
    id: "routes/tools.thermal-inertia";
    page: "/tools/thermal-inertia";
  };
  "routes/fruits_.all-projects.tsx": {
    id: "routes/fruits_.all-projects";
    page: "/fruits/all-projects";
  };
  "routes/fruits_.projects.$id.tsx": {
    id: "routes/fruits_.projects.$id";
    page: "/fruits/projects/:id";
  };
  "routes/tools.erv-calculator.tsx": {
    id: "routes/tools.erv-calculator";
    page: "/tools/erv-calculator";
  };
  "routes/tools.space-layout.tsx": {
    id: "routes/tools.space-layout";
    page: "/tools/space-layout";
  };
  "routes/fruits_.daily-log.tsx": {
    id: "routes/fruits_.daily-log";
    page: "/fruits/daily-log";
  };
  "routes/good.architecture.tsx": {
    id: "routes/good.architecture";
    page: "/good/architecture";
  };
  "routes/tools.do-not-use.tsx": {
    id: "routes/tools.do-not-use";
    page: "/tools/do-not-use";
  };
  "routes/good.consulting.tsx": {
    id: "routes/good.consulting";
    page: "/good/consulting";
  };
  "routes/assemblies.$id.tsx": {
    id: "routes/assemblies.$id";
    page: "/assemblies/:id";
  };
  "routes/docs.wc-waiver.tsx": {
    id: "routes/docs.wc-waiver";
    page: "/docs/wc-waiver";
  };
  "routes/fruits_.styles.tsx": {
    id: "routes/fruits_.styles";
    page: "/fruits/styles";
  };
  "routes/good.sunny-no1.tsx": {
    id: "routes/good.sunny-no1";
    page: "/good/sunny-no1";
  };
  "routes/sunny-home-no1.tsx": {
    id: "routes/sunny-home-no1";
    page: "/sunny-home-no1";
  };
  "routes/fruits_.vault.tsx": {
    id: "routes/fruits_.vault";
    page: "/fruits/vault";
  };
  "routes/good.building.tsx": {
    id: "routes/good.building";
    page: "/good/building";
  };
  "routes/materials.$id.tsx": {
    id: "routes/materials.$id";
    page: "/materials/:id";
  };
  "routes/card.$fileId.tsx": {
    id: "routes/card.$fileId";
    page: "/card/:fileId";
  };
  "routes/roots._index.tsx": {
    id: "routes/roots._index";
    page: "/roots";
  };
  "routes/tools._index.tsx": {
    id: "routes/tools._index";
    page: "/tools";
  };
  "routes/good.guides.tsx": {
    id: "routes/good.guides";
    page: "/good/guides";
  };
  "routes/science.$id.tsx": {
    id: "routes/science.$id";
    page: "/science/:id";
  };
  "routes/stories.$id.tsx": {
    id: "routes/stories.$id";
    page: "/stories/:id";
  };
  "routes/tools.loads.tsx": {
    id: "routes/tools.loads";
    page: "/tools/loads";
  };
  "routes/api.upload.tsx": {
    id: "routes/api.upload";
    page: "/api/upload" | "/api/upload/presign";
  };
  "routes/api.upload.presign.tsx": {
    id: "routes/api.upload.presign";
    page: "/api/upload/presign";
  };
  "routes/magic-link.tsx": {
    id: "routes/magic-link";
    page: "/magic-link";
  };
  "routes/api.vault.tsx": {
    id: "routes/api.vault";
    page: "/api/vault" | "/api/vault/multipart-complete" | "/api/vault/download/:fileId" | "/api/vault/archive-cleanup" | "/api/vault/multipart-abort" | "/api/vault/multipart-init" | "/api/vault/multipart-part" | "/api/vault/:fileId" | "/api/vault/folders" | "/api/vault/folders/:folderId" | "/api/vault/presign" | "/api/vault/upload";
  };
  "routes/api.vault.multipart-complete.tsx": {
    id: "routes/api.vault.multipart-complete";
    page: "/api/vault/multipart-complete";
  };
  "routes/api.vault.download.$fileId.tsx": {
    id: "routes/api.vault.download.$fileId";
    page: "/api/vault/download/:fileId";
  };
  "routes/api.vault.archive-cleanup.tsx": {
    id: "routes/api.vault.archive-cleanup";
    page: "/api/vault/archive-cleanup";
  };
  "routes/api.vault.multipart-abort.tsx": {
    id: "routes/api.vault.multipart-abort";
    page: "/api/vault/multipart-abort";
  };
  "routes/api.vault.multipart-init.tsx": {
    id: "routes/api.vault.multipart-init";
    page: "/api/vault/multipart-init";
  };
  "routes/api.vault.multipart-part.tsx": {
    id: "routes/api.vault.multipart-part";
    page: "/api/vault/multipart-part";
  };
  "routes/api.vault.$fileId.tsx": {
    id: "routes/api.vault.$fileId";
    page: "/api/vault/:fileId";
  };
  "routes/api.vault.folders.tsx": {
    id: "routes/api.vault.folders";
    page: "/api/vault/folders" | "/api/vault/folders/:folderId";
  };
  "routes/api.vault.folders.$folderId.tsx": {
    id: "routes/api.vault.folders.$folderId";
    page: "/api/vault/folders/:folderId";
  };
  "routes/api.vault.presign.tsx": {
    id: "routes/api.vault.presign";
    page: "/api/vault/presign";
  };
  "routes/api.vault.upload.tsx": {
    id: "routes/api.vault.upload";
    page: "/api/vault/upload";
  };
  "routes/tools.mtf.tsx": {
    id: "routes/tools.mtf";
    page: "/tools/mtf";
  };
  "routes/scc-demo.tsx": {
    id: "routes/scc-demo";
    page: "/scc-demo";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/explore.tsx": {
    id: "routes/explore";
    page: "/explore";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/fruits.tsx": {
    id: "routes/fruits";
    page: "/fruits";
  };
  "routes/good.s.tsx": {
    id: "routes/good.s";
    page: "/good/s";
  };
  "routes/health.tsx": {
    id: "routes/health";
    page: "/health" | "/health/:key?";
  };
  "routes/health.($key).tsx": {
    id: "routes/health.($key)";
    page: "/health/:key?";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/verify.tsx": {
    id: "routes/verify";
    page: "/verify";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/mrgnt.tsx": {
    id: "routes/mrgnt";
    page: "/mrgnt" | "/mrgnt/projects" | "/mrgnt/discord" | "/mrgnt/humans" | "/mrgnt/gbs";
  };
  "routes/mrgnt.projects.tsx": {
    id: "routes/mrgnt.projects";
    page: "/mrgnt/projects";
  };
  "routes/mrgnt.discord.tsx": {
    id: "routes/mrgnt.discord";
    page: "/mrgnt/discord";
  };
  "routes/mrgnt._index.tsx": {
    id: "routes/mrgnt._index";
    page: "/mrgnt";
  };
  "routes/mrgnt.humans.tsx": {
    id: "routes/mrgnt.humans";
    page: "/mrgnt/humans";
  };
  "routes/mrgnt.gbs.tsx": {
    id: "routes/mrgnt.gbs";
    page: "/mrgnt/gbs";
  };
  "routes/path.tsx": {
    id: "routes/path";
    page: "/path" | "/path/faq-1" | "/path/faq-2" | "/path/faq-3" | "/path/faq-4" | "/path/faq-5" | "/path/faq-6" | "/path/faq-7";
  };
  "routes/path._index.tsx": {
    id: "routes/path._index";
    page: "/path";
  };
  "routes/path.faq-1.tsx": {
    id: "routes/path.faq-1";
    page: "/path/faq-1";
  };
  "routes/path.faq-2.tsx": {
    id: "routes/path.faq-2";
    page: "/path/faq-2";
  };
  "routes/path.faq-3.tsx": {
    id: "routes/path.faq-3";
    page: "/path/faq-3";
  };
  "routes/path.faq-4.tsx": {
    id: "routes/path.faq-4";
    page: "/path/faq-4";
  };
  "routes/path.faq-5.tsx": {
    id: "routes/path.faq-5";
    page: "/path/faq-5";
  };
  "routes/path.faq-6.tsx": {
    id: "routes/path.faq-6";
    page: "/path/faq-6";
  };
  "routes/path.faq-7.tsx": {
    id: "routes/path.faq-7";
    page: "/path/faq-7";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/fruits_.good-building-system_.$id": typeof import("./app/routes/fruits_.good-building-system_.$id.tsx");
  "routes/fruits_.good-building-system_.new": typeof import("./app/routes/fruits_.good-building-system_.new.tsx");
  "routes/fruits_.good-building-system": typeof import("./app/routes/fruits_.good-building-system.tsx");
  "routes/tools.frames-volume-calc": typeof import("./app/routes/tools.frames-volume-calc.tsx");
  "routes/tools.grade-differential": typeof import("./app/routes/tools.grade-differential.tsx");
  "routes/tools.building-envelope": typeof import("./app/routes/tools.building-envelope.tsx");
  "routes/grandpas-cabin-recipe": typeof import("./app/routes/grandpas-cabin-recipe.tsx");
  "routes/tools.thermal-inertia": typeof import("./app/routes/tools.thermal-inertia.tsx");
  "routes/fruits_.all-projects": typeof import("./app/routes/fruits_.all-projects.tsx");
  "routes/fruits_.projects.$id": typeof import("./app/routes/fruits_.projects.$id.tsx");
  "routes/tools.erv-calculator": typeof import("./app/routes/tools.erv-calculator.tsx");
  "routes/tools.space-layout": typeof import("./app/routes/tools.space-layout.tsx");
  "routes/fruits_.daily-log": typeof import("./app/routes/fruits_.daily-log.tsx");
  "routes/good.architecture": typeof import("./app/routes/good.architecture.tsx");
  "routes/tools.do-not-use": typeof import("./app/routes/tools.do-not-use.tsx");
  "routes/good.consulting": typeof import("./app/routes/good.consulting.tsx");
  "routes/assemblies.$id": typeof import("./app/routes/assemblies.$id.tsx");
  "routes/docs.wc-waiver": typeof import("./app/routes/docs.wc-waiver.tsx");
  "routes/fruits_.styles": typeof import("./app/routes/fruits_.styles.tsx");
  "routes/good.sunny-no1": typeof import("./app/routes/good.sunny-no1.tsx");
  "routes/sunny-home-no1": typeof import("./app/routes/sunny-home-no1.tsx");
  "routes/fruits_.vault": typeof import("./app/routes/fruits_.vault.tsx");
  "routes/good.building": typeof import("./app/routes/good.building.tsx");
  "routes/materials.$id": typeof import("./app/routes/materials.$id.tsx");
  "routes/card.$fileId": typeof import("./app/routes/card.$fileId.tsx");
  "routes/roots._index": typeof import("./app/routes/roots._index.tsx");
  "routes/tools._index": typeof import("./app/routes/tools._index.tsx");
  "routes/good.guides": typeof import("./app/routes/good.guides.tsx");
  "routes/science.$id": typeof import("./app/routes/science.$id.tsx");
  "routes/stories.$id": typeof import("./app/routes/stories.$id.tsx");
  "routes/tools.loads": typeof import("./app/routes/tools.loads.tsx");
  "routes/api.upload": typeof import("./app/routes/api.upload.tsx");
  "routes/api.upload.presign": typeof import("./app/routes/api.upload.presign.tsx");
  "routes/magic-link": typeof import("./app/routes/magic-link.tsx");
  "routes/api.vault": typeof import("./app/routes/api.vault.tsx");
  "routes/api.vault.multipart-complete": typeof import("./app/routes/api.vault.multipart-complete.tsx");
  "routes/api.vault.download.$fileId": typeof import("./app/routes/api.vault.download.$fileId.tsx");
  "routes/api.vault.archive-cleanup": typeof import("./app/routes/api.vault.archive-cleanup.tsx");
  "routes/api.vault.multipart-abort": typeof import("./app/routes/api.vault.multipart-abort.tsx");
  "routes/api.vault.multipart-init": typeof import("./app/routes/api.vault.multipart-init.tsx");
  "routes/api.vault.multipart-part": typeof import("./app/routes/api.vault.multipart-part.tsx");
  "routes/api.vault.$fileId": typeof import("./app/routes/api.vault.$fileId.tsx");
  "routes/api.vault.folders": typeof import("./app/routes/api.vault.folders.tsx");
  "routes/api.vault.folders.$folderId": typeof import("./app/routes/api.vault.folders.$folderId.tsx");
  "routes/api.vault.presign": typeof import("./app/routes/api.vault.presign.tsx");
  "routes/api.vault.upload": typeof import("./app/routes/api.vault.upload.tsx");
  "routes/tools.mtf": typeof import("./app/routes/tools.mtf.tsx");
  "routes/scc-demo": typeof import("./app/routes/scc-demo.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/explore": typeof import("./app/routes/explore.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/fruits": typeof import("./app/routes/fruits.tsx");
  "routes/good.s": typeof import("./app/routes/good.s.tsx");
  "routes/health": typeof import("./app/routes/health.tsx");
  "routes/health.($key)": typeof import("./app/routes/health.($key).tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/verify": typeof import("./app/routes/verify.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/mrgnt": typeof import("./app/routes/mrgnt.tsx");
  "routes/mrgnt.projects": typeof import("./app/routes/mrgnt.projects.tsx");
  "routes/mrgnt.discord": typeof import("./app/routes/mrgnt.discord.tsx");
  "routes/mrgnt._index": typeof import("./app/routes/mrgnt._index.tsx");
  "routes/mrgnt.humans": typeof import("./app/routes/mrgnt.humans.tsx");
  "routes/mrgnt.gbs": typeof import("./app/routes/mrgnt.gbs.tsx");
  "routes/path": typeof import("./app/routes/path.tsx");
  "routes/path._index": typeof import("./app/routes/path._index.tsx");
  "routes/path.faq-1": typeof import("./app/routes/path.faq-1.tsx");
  "routes/path.faq-2": typeof import("./app/routes/path.faq-2.tsx");
  "routes/path.faq-3": typeof import("./app/routes/path.faq-3.tsx");
  "routes/path.faq-4": typeof import("./app/routes/path.faq-4.tsx");
  "routes/path.faq-5": typeof import("./app/routes/path.faq-5.tsx");
  "routes/path.faq-6": typeof import("./app/routes/path.faq-6.tsx");
  "routes/path.faq-7": typeof import("./app/routes/path.faq-7.tsx");
};